import type { Sensor } from "./types";

/**
 * Placeholder sensor data matching the Sensors REST API schema.
 * Includes ocean buoys, river sensors, farm/weather stations, and air quality monitors
 * spread across continents and oceans.
 */
export const PLACEHOLDER_SENSORS: Sensor[] = [
  // Ocean / buoys
  {
    id: "a1b2c3d4-0001-4000-8000-000000000001",
    external_id: "46108",
    name: "NDBC Station 46108",
    description: "Ocean observation buoy, Pacific",
    sensor_type: "buoy",
    status: "active",
    deployment_date: "2020-01-15",
    decommissioned_date: null,
    latitude: 37.5,
    longitude: -122.5,
    provider_id: "p-noaa",
    provider_name: "NOAA",
    provider_slug: "noaa",
    feed_id: "f-ndbc",
    feed_name: "NDBC Buoys",
    connected_service: "ndbc",
    last_reading_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "a1b2c3d4-0002-4000-8000-000000000002",
    external_id: "44008",
    name: "NDBC Station 44008",
    description: "Ocean buoy, East Coast",
    sensor_type: "buoy",
    status: "active",
    deployment_date: "2019-06-01",
    decommissioned_date: null,
    latitude: 40.5,
    longitude: -69.25,
    provider_id: "p-noaa",
    provider_name: "NOAA",
    provider_slug: "noaa",
    feed_id: "f-ndbc",
    feed_name: "NDBC Buoys",
    connected_service: "ndbc",
    last_reading_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "a1b2c3d4-0003-4000-8000-000000000003",
    external_id: "51001",
    name: "NDBC Station 51001",
    description: "Pacific Ocean buoy",
    sensor_type: "buoy",
    status: "active",
    deployment_date: "2018-03-10",
    decommissioned_date: null,
    latitude: 24.5,
    longitude: -155.0,
    provider_id: "p-noaa",
    provider_name: "NOAA",
    provider_slug: "noaa",
    feed_id: "f-ndbc",
    feed_name: "NDBC Buoys",
    connected_service: "ndbc",
  },
  {
    id: "a1b2c3d4-0004-4000-8000-000000000004",
    external_id: "eu-buoy-1",
    name: "EMODnet Buoy North Sea",
    description: "European ocean monitoring buoy",
    sensor_type: "buoy",
    status: "active",
    deployment_date: "2021-04-01",
    decommissioned_date: null,
    latitude: 54.0,
    longitude: 4.5,
    provider_id: "p-emodnet",
    provider_name: "EMODnet",
    provider_slug: "emodnet",
    feed_id: "f-eu-ocean",
    feed_name: "EU Ocean Buoys",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0005-4000-8000-000000000005",
    external_id: "au-buoy-1",
    name: "IMOS Southern Ocean Buoy",
    description: "Australian ocean sensor",
    sensor_type: "buoy",
    status: "active",
    deployment_date: "2020-11-20",
    decommissioned_date: null,
    latitude: -42.0,
    longitude: 145.0,
    provider_id: "p-imos",
    provider_name: "IMOS",
    provider_slug: "imos",
    feed_id: "f-imos",
    feed_name: "IMOS Buoys",
    connected_service: null,
  },
  // River sensors
  {
    id: "a1b2c3d4-0010-4000-8000-000000000010",
    external_id: "usgs-01364890",
    name: "Hudson River at Poughkeepsie",
    description: "USGS stream gauge",
    sensor_type: "river_sensor",
    status: "active",
    deployment_date: "2015-05-01",
    decommissioned_date: null,
    latitude: 41.7065,
    longitude: -73.9284,
    provider_id: "p-usgs",
    provider_name: "USGS",
    provider_slug: "usgs",
    feed_id: "f-usgs-wqp",
    feed_name: "USGS Water Quality",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0011-4000-8000-000000000011",
    external_id: "usgs-05570500",
    name: "Mississippi River at St. Louis",
    description: "USGS stream gauge",
    sensor_type: "river_sensor",
    status: "active",
    deployment_date: "2010-01-01",
    decommissioned_date: null,
    latitude: 38.8014,
    longitude: -90.1523,
    provider_id: "p-usgs",
    provider_name: "USGS",
    provider_slug: "usgs",
    feed_id: "f-usgs-wqp",
    feed_name: "USGS Water Quality",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0012-4000-8000-000000000012",
    external_id: "thames-001",
    name: "Thames River Monitoring Station",
    description: "UK Environment Agency river sensor",
    sensor_type: "river_sensor",
    status: "active",
    deployment_date: "2018-09-15",
    decommissioned_date: null,
    latitude: 51.5074,
    longitude: -0.1278,
    provider_id: "p-ea-uk",
    provider_name: "Environment Agency",
    provider_slug: "ea-uk",
    feed_id: "f-thames",
    feed_name: "Thames Monitoring",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0013-4000-8000-000000000013",
    external_id: "ganges-varanasi",
    name: "Ganges at Varanasi",
    description: "River water quality monitor",
    sensor_type: "river_sensor",
    status: "active",
    deployment_date: "2022-02-01",
    decommissioned_date: null,
    latitude: 25.3176,
    longitude: 83.0059,
    provider_id: "p-cpcb",
    provider_name: "CPCB",
    provider_slug: "cpcb",
    feed_id: "f-ganges",
    feed_name: "Ganges Monitoring",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0014-4000-8000-000000000014",
    external_id: "amazon-manaus",
    name: "Amazon River at Manaus",
    description: "Hydrology and water quality",
    sensor_type: "river_sensor",
    status: "active",
    deployment_date: "2019-07-01",
    decommissioned_date: null,
    latitude: -3.1190,
    longitude: -60.0217,
    provider_id: "p-ana-br",
    provider_name: "ANA Brazil",
    provider_slug: "ana-br",
    feed_id: "f-amazon",
    feed_name: "Amazon Basin",
    connected_service: null,
  },
  // Farm / weather stations
  {
    id: "a1b2c3d4-0020-4000-8000-000000000020",
    external_id: "farm-iowa-01",
    name: "Iowa Corn Field Station A",
    description: "Farm weather and soil sensor",
    sensor_type: "weather_station",
    status: "active",
    deployment_date: "2021-04-10",
    decommissioned_date: null,
    latitude: 41.5868,
    longitude: -93.6250,
    provider_id: "p-farmnet",
    provider_name: "FarmNet",
    provider_slug: "farmnet",
    feed_id: "f-midwest",
    feed_name: "Midwest Farm Network",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0021-4000-8000-000000000021",
    external_id: "farm-netherlands-01",
    name: "Dutch Dairy Farm Sensor",
    description: "Pasture and weather monitoring",
    sensor_type: "weather_station",
    status: "active",
    deployment_date: "2020-08-01",
    decommissioned_date: null,
    latitude: 52.1326,
    longitude: 5.2913,
    provider_id: "p-wageningen",
    provider_name: "Wageningen",
    provider_slug: "wageningen",
    feed_id: "f-eu-farms",
    feed_name: "EU Farm Sensors",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0022-4000-8000-000000000022",
    external_id: "farm-argentina-01",
    name: "Pampas Soy Field Station",
    description: "Agricultural weather station",
    sensor_type: "weather_station",
    status: "active",
    deployment_date: "2022-01-15",
    decommissioned_date: null,
    latitude: -34.6037,
    longitude: -58.3816,
    provider_id: "p-inta",
    provider_name: "INTA",
    provider_slug: "inta",
    feed_id: "f-pampas",
    feed_name: "Pampas Agriculture",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0023-4000-8000-000000000023",
    external_id: "farm-india-punjab",
    name: "Punjab Wheat Field Sensor",
    description: "Irrigation and weather",
    sensor_type: "weather_station",
    status: "active",
    deployment_date: "2021-11-01",
    decommissioned_date: null,
    latitude: 30.9010,
    longitude: 75.8573,
    provider_id: "p-icar",
    provider_name: "ICAR",
    provider_slug: "icar",
    feed_id: "f-punjab",
    feed_name: "Punjab Farm Network",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0024-4000-8000-000000000024",
    external_id: "farm-kenya-01",
    name: "Kenya Tea Estate Weather",
    description: "Highland farm weather station",
    sensor_type: "weather_station",
    status: "active",
    deployment_date: "2023-03-01",
    decommissioned_date: null,
    latitude: -0.4201,
    longitude: 36.9475,
    provider_id: "p-kalro",
    provider_name: "KALRO",
    provider_slug: "kalro",
    feed_id: "f-kenya-farms",
    feed_name: "Kenya Agriculture",
    connected_service: null,
  },
  // Air quality
  {
    id: "a1b2c3d4-0030-4000-8000-000000000030",
    external_id: "purpleair-la-01",
    name: "Los Angeles PM2.5 Monitor",
    description: "Community air quality sensor",
    sensor_type: "air_quality_monitor",
    status: "active",
    deployment_date: "2019-05-20",
    decommissioned_date: null,
    latitude: 34.0522,
    longitude: -118.2437,
    provider_id: "p-purpleair",
    provider_name: "PurpleAir",
    provider_slug: "purpleair",
    feed_id: "f-airnow",
    feed_name: "AirNow",
    connected_service: "airnow",
  },
  {
    id: "a1b2c3d4-0031-4000-8000-000000000031",
    external_id: "aqi-chicago-01",
    name: "Chicago Air Quality Station",
    description: "EPA AirNow monitor",
    sensor_type: "air_quality_monitor",
    status: "active",
    deployment_date: "2018-01-01",
    decommissioned_date: null,
    latitude: 41.8781,
    longitude: -87.6298,
    provider_id: "p-epa",
    provider_name: "EPA",
    provider_slug: "epa",
    feed_id: "f-airnow",
    feed_name: "AirNow",
    connected_service: "airnow",
  },
  {
    id: "a1b2c3d4-0032-4000-8000-000000000032",
    external_id: "aqi-delhi-01",
    name: "Delhi PM2.5 Monitor",
    description: "CPCB air quality station",
    sensor_type: "air_quality_monitor",
    status: "active",
    deployment_date: "2020-10-01",
    decommissioned_date: null,
    latitude: 28.7041,
    longitude: 77.1025,
    provider_id: "p-cpcb",
    provider_name: "CPCB",
    provider_slug: "cpcb",
    feed_id: "f-india-aqi",
    feed_name: "India AQI",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0033-4000-8000-000000000033",
    external_id: "aqi-beijing-01",
    name: "Beijing Air Quality Station",
    description: "National monitoring network",
    sensor_type: "air_quality_monitor",
    status: "active",
    deployment_date: "2017-06-01",
    decommissioned_date: null,
    latitude: 39.9042,
    longitude: 116.4074,
    provider_id: "p-mep",
    provider_name: "MEP China",
    provider_slug: "mep",
    feed_id: "f-china-aqi",
    feed_name: "China AQI",
    connected_service: null,
  },
  {
    id: "a1b2c3d4-0034-4000-8000-000000000034",
    external_id: "aqi-london-01",
    name: "London King's Cross AQ",
    description: "DEFRA air quality monitor",
    sensor_type: "air_quality_monitor",
    status: "active",
    deployment_date: "2019-09-01",
    decommissioned_date: null,
    latitude: 51.5300,
    longitude: -0.1239,
    provider_id: "p-defra",
    provider_name: "DEFRA",
    provider_slug: "defra",
    feed_id: "f-uk-aq",
    feed_name: "UK Air Quality",
    connected_service: null,
  },
];

/** Sensor types present in placeholder data (for filter UI when not using API). */
export const PLACEHOLDER_SENSOR_TYPES = [
  "buoy",
  "river_sensor",
  "weather_station",
  "air_quality_monitor",
] as const;
